# Generated by Django 2.1.1 on 2018-09-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='games_played_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='games_won_field',
            field=models.IntegerField(default=0),
        ),
    ]
